baseURL = "https://docs.lucidarch.dev"
title = "Lucid"
theme = "docport"
googleAnalytics = "UA-96232175-1"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]
pygmentsUseClasses = true
pygmentsCodefences = true
enableGitInfo = true
ignoreFiles = ["README.md"]

[outputs]
home = ["HTML", "JSON"]

[imaging.exif]
disableDate = true
disableLatLong = true

[params]
color_main = "gray"
color_second = "#17a3b8"
ordersectionsby = "weight"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "borland"
    tabWidth = 4
